### ISSUE TITLE
校园网连接不成功

### ISSUE THREAD

**Issue by FYBNB** [YINGHAIDADA/School_Network_AutoConnecter#1]
Traceback (most recent call last):
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10065] 套接字操作尝试一个无法连接的主机。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "E:\Project\environment Path\Python3.9\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "E:\Project\environment Path\Python3.9\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "E:\Project\environment Path\Python3.9\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\Project\environment Path\Python3.9\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "E:\Project\environment Path\Python3.9\lib\http\client.py", line 950, in send
    self.connect()
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000025453647A30>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project\environment Path\Python3.9\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\Project\environment Path\Python3.9\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.16.253.3', port=801): Max retries exceeded with url: /eportal/?c=Portal&a=login&callback=dr1003&login_method=1&user_account=Q22301190&user_password=200519&wlan_user_ip=192.168.32.232&wlan_user_ipv6=&wlan_user_mac=000000000000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025453647A30>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project\School_Network_AutoConnecter-main\AutoConnect.py", line 65, in <module>
    a.Login()
  File "E:\Project\School_Network_AutoConnecter-main\AutoConnect.py", line 43, in Login
    res = requests.get(URL)
  File "E:\Project\environment Path\Python3.9\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\Project\environment Path\Python3.9\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Project\environment Path\Python3.9\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Project\environment Path\Python3.9\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\Project\environment Path\Python3.9\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.16.253.3', port=801): Max retries exceeded with url: /eportal/?c=Portal&a=login&callback=dr1003&login_method=1&user_account=Q22301190&user_password=211019&wlan_user_ip=192.168.32.232&wlan_user_ipv6=&wlan_user_mac=000000000000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025453647A30>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
请按任意键继续. . .

**Comment by FYBNB** [comment]
![image](https://user-images.githubusercontent.com/57937178/196649102-9755365f-8d19-4f25-99b3-6424ef78106e.png)
<img width="503" alt="image" src="https://user-images.githubusercontent.com/57937178/196649209-3dbcfa90-5a9b-4e41-bfca-0d25fcb5a11e.png">

**Comment by YINGHAIDADA** [comment]
> ![image](https://user-images.githubusercontent.com/57937178/196649102-9755365f-8d19-4f25-99b3-6424ef78106e.png) <img alt="image" width="503" src="https://user-images.githubusercontent.com/57937178/196649209-3dbcfa90-5a9b-4e41-bfca-0d25fcb5a11e.png">

我更新了README文档中DEBUG部分 [点击](https://github.com/YINGHAIDADA/School_Network_AutoConnecter/blob/main/doc/debug.md)，中间提到了如何检查，原本是否有效

**Comment by YINGHAIDADA** [comment]
> ![image](https://user-images.githubusercontent.com/57937178/196649102-9755365f-8d19-4f25-99b3-6424ef78106e.png)
> <img alt="image" width="503" src="https://user-images.githubusercontent.com/57937178/196649209-3dbcfa90-5a9b-4e41-bfca-0d25fcb5a11e.png">

已解决，关于`无线网络`的连接方式需要保证原本已连接了`Wi-Fi`，这样才能自动登录校园网

**Comment by YINGHAIDADA** [comment]
> ![image](https://user-images.githubusercontent.com/57937178/196649102-9755365f-8d19-4f25-99b3-6424ef78106e.png)
> <img alt="image" width="503" src="https://user-images.githubusercontent.com/57937178/196649209-3dbcfa90-5a9b-4e41-bfca-0d25fcb5a11e.png">

已解决，关于`无线网络`的连接方式需要保证原本已连接了`Wi-Fi`，这样才能自动登录校园网
